1. Импорт библиотеки NumPy с общепринятым сокращением.


In [1]:
import numpy as np

2. Примеры создания массивов:
   - из обычных списков;
   - с использованием функций `zeros`, `ones`, `arange` или аналогичных.

In [9]:
arr = np.array([[1, 2, 3],
                [4,5,6],
                [7,8,9]])

# Такой же массив что и сверху 
arr2 = np.arange(1, 10, 1).reshape(3, 3)



zeros_arr = np.zeros((3, 3)) # нолики

ones_arr = np.ones((3,3)) # единички



Последний столбик из каждого массива

In [12]:
print(arr[:, -1])

print(arr2[:, -1])
print(zeros_arr[:, -1])
print(ones_arr[:, -1])

[3 6 9]
[3 6 9]
[0. 0. 0.]
[1. 1. 1.]


3. Демонстрация атрибутов:
   - вывод формы (shape) и типа данных (dtype) для одного из массивов.

In [ ]:
arr2.shape, arr2.dtype # shape выводит размерность массива | dtype выводит тип данных

((3, 3), dtype('int64'))

4. Примеры индексирования и срезов:
   - получение отдельного элемента;
   - извлечение подмассива с помощью среза.

In [20]:
np.array([arr2[0, 0], arr2[0, 1], arr2[0, 2]])

array([1, 2, 3])

In [21]:
arr2[0, :]

array([1, 2, 3])

5. Примеры векторных операций и базовых статистик:
   - поэлементное сложение или умножение массивов;
   - вычисление средней величины (`mean`) или другой простой статистики.

In [22]:
arr2 += 1
arr2

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [24]:
arr2 -= 3
arr2

array([[-4, -3, -2],
       [-1,  0,  1],
       [ 2,  3,  4]])

In [ ]:
arr2 *= arr  # поэлементно умножает

arr2

array([[-4, -6, -6],
       [-4,  0,  6],
       [14, 24, 36]])

In [ ]:
print("Среднее:", arr2.mean())
print("Медиана:", np.median(arr2))

Среднее: 6.666666666666667
Медиана: 0.0
